apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-management
  namespace: product-management
spec:
  replicas: 3
  selector:
    matchLabels:
      app: product-management
  template:
    metadata:
      labels:
        app: product-management
    spec:
      containers:
        - name: product-management
          image: docker.io/library/product-management:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: product-management-config
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
