apiVersion: v1
kind: ConfigMap
metadata:
    name: scripts
    namespace: k6
data:
    load_test.js: |
        import http from 'k6/http';
        import { check } from 'k6';

        export const options = {
            scenarios: {
                constant_load: {
                    executor: 'constant-arrival-rate',
                    rate: 5000,
                    timeUnit: '1s',
                    duration: '30m',
                    preAllocatedVUs: 100,
                    maxVUs: 500,
                },
            },
        };

        export default function () {
            const id = Math.floor(Math.random() * 50000000) + 1;
            const res = http.get(`http://orders.orders/orders?order_id=${id}`, {
                headers: { 'X-User-Id': '1' },
                tags: { name: 'get_order' },
            });
            
            check(res, {
                'status 200': (r) => r.status === 200,
            });
        }
