apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: products-infra
spec:
  ports:
    - port: 9200
      name: http
    - port: 9300
      name: transport
  selector:
    app: elasticsearch
  clusterIP: None
