apiVersion: v1
kind: Namespace
metadata:
  name: product-management

---
apiVersion: v1
kind: Namespace
metadata:
  name: product-management-infra

---
apiVersion: v1
kind: Namespace
metadata:
  name: products

---
apiVersion: v1
kind: Namespace
metadata:
  name: products-infra

---
apiVersion: v1
kind: Namespace
metadata:
  name: orders

---
apiVersion: v1
kind: Namespace
metadata:
  name: orders-infra

---
apiVersion: v1
kind: Namespace
metadata:
  name: payments

---
apiVersion: v1
kind: Namespace
metadata:
  name: payments-infra

---
apiVersion: v1
kind: Namespace
metadata:
  name: delivery

---
apiVersion: v1
kind: Namespace
metadata:
  name: delivery-infra

---
apiVersion: v1
kind: Namespace
metadata:
  name: kafka-common
